/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/10128/Documents/AnlogicProjects/pulpino_zeroriscy/al_ip/clkgen.v
 ** Date	:	2021 03 19
 ** TD version	:	5.0.24498
\************************************************************/

`timescale 1ns / 1ps

module OSC0 ( osc_dis, osc_clk );
	output 		 osc_clk;
	input  		 osc_dis;

		EG_PHY_OSC #(
		.STDBY("ENABLE"))
		inst(
		.osc_clk(osc_clk),
		.osc_dis(osc_dis));

endmodule