/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/10128/Documents/AnlogicProjects/pulpino_zeroriscy/al_ip/mem_blk.v
 ** Date	:	2021 03 30
 ** TD version	:	5.0.24498
\************************************************************/

`timescale 1ns / 1ps

module mem_blk
	#( parameter CHIP_NO = 0)
 ( doa, dia, addra, cea, clka, wea );


	localparam DATA_WIDTH_A = 32; 
	localparam ADDR_WIDTH_A = 8;
	localparam DATA_DEPTH_A = 256;
	localparam DATA_WIDTH_B = 32;
	localparam ADDR_WIDTH_B = 8;
	localparam DATA_DEPTH_B = 256;
	localparam REGMODE_A    = "NOREG";
	localparam WRITEMODE_A  = "NORMAL";

	localparam string FILE_LOCATION [15:0] = {
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_15.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_14.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_13.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_12.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_11.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_10.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_9.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_8.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_7.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_6.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_5.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_4.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_3.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_2.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_1.mif",
		"/media/barneyzhu/570A48D089F2FF71/pulpino_project/uart_to_mem/ext_mem_0.mif"
	};

	output [DATA_WIDTH_A-1:0] doa;

	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [3:0] wea;
	input  cea;
	input  clka;


	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.BYTE_ENABLE(8),
				.BYTE_A(4),
				.BYTE_B(4),
				.MODE("SP"),
				.REGMODE_A(REGMODE_A),
				.WRITEMODE_A(WRITEMODE_A),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE(FILE_LOCATION[CHIP_NO]),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb({8{1'b0}}),
				.cea(cea),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());

endmodule
